### ISSUE TITLE
Warnings logged when using Spring 4.3.17

### ISSUE THREAD

**Issue by GuiForget** [nebula-plugins/gradle-resolution-rules#38]
The following warning is logged when using Spring 4.3.17.RELEASE:

Resolution rule AlignRule(name=null, group=org\.springframework, includes=[spring-(tx|aop|instrument|context-support|beans|jms|test|core|oxm|web|context|expression|aspects|websocket|framework-bom|webmvc|webmvc-portlet|jdbc|orm|instrument-tomcat|messaging)], excludes=[], match=[2-9]\.[0-9]\.[0-9].RELEASE, ruleSet=align-spring, reason=Align Spring, author=Danny Thomas <dannyt@netflix.com>, date=2016-05-16) is unable to honor match. [2-9]\.[0-9]\.[0-9].RELEASE does not match 4.3.17.RELEASE. Will use 4.3.17.RELEASE

This is due to an incorrect regexp in align-spring.

**Comment by GuiForget** [comment]
I have the fix for this here already: https://github.com/nebula-plugins/gradle-resolution-rules/pull/37

**Comment by sghill** [comment]
@GuiForget which version of the gradle-resolution-rules-plugin are you using?

**Comment by GuiForget** [comment]
5.1.0 I believe. I'm in the process of upgrading to Gradle 4.10 and therefore will upgrade to v. 7.0.2 at the same time.

**Comment by rahulsom** [comment]
#37 has been merged.
